# Generated by Django 4.1.1 on 2023-08-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('employee', 'Employee')], default='employee', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='probation',
            field=models.IntegerField(default=0, help_text='Probation in days'),
        ),
    ]
